# Generated by Django 5.2.12 on 2026-04-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_admin_mode_enabled_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_app_password",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
