# Generated by Django 5.2.12 on 2026-04-07 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_change_event_date_to_datetime"),
        ("students", "0003_student_user_student_students_st_user_id_e808e6_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("confirmed", "Confirmado"),
                    ("attended", "Asistió"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="instructor_bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="instructor_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="invitation_message",
            field=models.TextField(
                blank=True,
                default="Has sido invitado a participar en este evento. ¡Te esperamos!",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="max_capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="attendance",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("accepted", "Aceptado"),
                            ("declined", "Rechazado"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "sent_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("both", "Ambos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="events.invitation",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="events_enro_status_55f42b_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["token"], name="events_invi_token_211537_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["student_email"], name="events_invi_student_9dccb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["status"], name="events_invi_status_f21291_idx"),
        ),
    ]
