# Generated by Django 5.2.12 on 2026-04-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_add_invitation_and_update_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name_font_size",
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name="event",
            name="name_x",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="event",
            name="name_y",
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name="event",
            name="template_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="event_templates/"
            ),
        ),
    ]
