# Generated by Django 5.2.12 on 2026-03-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificados", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="font_color",
            field=models.CharField(
                default="#000000", help_text="Color del texto", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="font_family",
            field=models.CharField(
                default="Helvetica-Bold", help_text="Fuente", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="font_size",
            field=models.IntegerField(default=24, help_text="Tamaño de fuente"),
        ),
        migrations.AddField(
            model_name="template",
            name="x_coord",
            field=models.FloatField(default=200, help_text="Posición X del nombre"),
        ),
        migrations.AddField(
            model_name="template",
            name="y_coord",
            field=models.FloatField(default=300, help_text="Posición Y del nombre"),
        ),
        migrations.AlterField(
            model_name="template",
            name="layout_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
