# Generated by Django 5.2.12 on 2026-04-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificados", "0004_template_font_color_template_font_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
